### ISSUE TITLE
Unexpected result when using 'omega' : 1.5 instead of 'omega' : [1.5] when assembling a test matrix

### ISSUE THREAD

**Issue by wlllind** [capytaine/capytaine#547] opened 2024-05-28 06:20 UTC
The following code is taken from the cookbook. The only changes I made are a decreased number of bodies (to speed things up) and the input for omega in the 'test_matrix' variable. The peculiar thing is that when setting 'omega' : 1.5 in the test_matrix variable yields different results than using 'omega' : [1.5]. The only difference is that omega is changed from a float to a list containing a float.  I have plotted the results for both cases  as well.

For this specific example the same trend is found. However, when performing a grid study on my own defined bodies, using 1.5 yields results that one would expect from a convergence study, but [1.5] does not. 

```python
import numpy as np
from numpy import pi
import xarray as xr
import matplotlib.pyplot as plt
import capytaine as cpt


def make_cylinder(resolution):
    """Make cylinder with a mesh of a given resolution in panels/meter."""
    radius = 1.0
    length = 5.0
    mesh = cpt.mesh_horizontal_cylinder(
        length=length, radius=radius,
        center=(0, 0, -1.5*radius),
        resolution=(int(resolution*radius),
                    int(2*pi*length*resolution),
                    int(length*resolution))
    )
    body = cpt.FloatingBody(mesh, name=f"cylinder_{mesh.nb_faces:04d}")
    # Store the number of panels in the name of the body
    body.add_translation_dof(name="Heave")
    return body


def read_nb_faces_in_mesh_name(ds):
    """Read the name of the body to guess the resolution of the mesh."""
    ds.coords['nb_faces'] = xr.DataArray([int(name[9:]) for name in ds['body_name'].values], coords=[ds['body_name']])
    ds = ds.swap_dims({'body_name': 'nb_faces'})
    return ds


test_matrix1 = xr.Dataset(coords={
    'omega': [1.5],
    'radiating_dof': ['Heave'],
})


test_matrix2 = xr.Dataset(coords={
    'omega': 1.5,
    'radiating_dof': ['Heave'],
})

bodies = [make_cylinder(n) for n in np.linspace(1, 3, 5)]
ds1 = cpt.BEMSolver(green_function=cpt.XieDelhommeau()).fill_dataset(test_matrix1, bodies)
ds2 = cpt.BEMSolver(green_function=cpt.XieDelhommeau()).fill_dataset(test_matrix2, bodies)


ds1 = read_nb_faces_in_mesh_name(ds1)
ds2 = read_nb_faces_in_mesh_name(ds2)

ds1['added_mass'].plot(x='nb_faces', label = '\'omega\':[1.5]')
ds2['added_mass'].plot(x='nb_faces',label = '\'omega\':1.5')


plt.legend()
plt.show()

```

![omegaInput](https://github.com/capytaine/capytaine/assets/99391740/f7ba33d8-8a84-4b48-8e09-97c71647e459)

**Comment by mancellin** [comment] 2024-05-28 08:10
The correct syntax is supposed to be `test_matrix1`.
Indeed, `test_matrix2` yields:
```python
print(ds2.omega.values)
# array([1.])
```
The good news is that `ds2` is self-consistent. The bad news is that it is not what you asked for. I'll look for the cause of that bug.

**Comment by mancellin** [comment] 2024-05-28 08:14
Short version of the bug:
```python
import xarray as xr
import capytaine as cpt

body = cpt.FloatingBody(mesh=cpt.mesh_sphere().immersed_part(), dofs=cpt.rigid_body_dofs())

test_matrix = xr.Dataset(coords={
    'omega': 1.5,
    'radiating_dof': ['Heave'],
})

ds = cpt.BEMSolver().fill_dataset(test_matrix, body)

print(test_matrix.omega.values, ds.omega.values)

```

**Comment by mancellin** [comment] 2024-05-28 08:31
So Capytaine raises an error if the test matrix has no field named like a frequency. But if there is one but it is not a list, then it ignores it and use the default value of $\omega = 1.0$.

```python
import xarray as xr
import capytaine as cpt

body = cpt.FloatingBody(mesh=cpt.mesh_sphere().immersed_part(), dofs=cpt.rigid_body_dofs())
test_matrix = xr.Dataset(coords={
    'omega': "potato",
    'radiating_dof': ['Heave'],
})
ds = cpt.BEMSolver().fill_dataset(test_matrix, body)
print(test_matrix.omega.values, ds.omega.values)
```

This is most likely a bug limited to frequency, because of its special property that it can be provided under different names (`"omega"`, `"wavelength"`, etc.).

**Comment by mancellin** [comment] 2024-05-28 08:45
I found the problem. It will be fixed in the next version. In the mean time, always use a list when providing a frequency to a test matrix.

Thank you for reporting this issue!

**Closed** 2024-05-28 09:31 UTC
Labels: bug
